version: "2.3"

services:

  # ROS Noetic + ROS 2 Eloquent
  bridge:
    image: ros:eloquent-ros1-bridge
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "ROS_DOMAIN_ID=0"
    command: ros2 run ros1_bridge dynamic_bridge


  # ROS Melodic rosbot hardware layer
  rosbot:
    image: husarion/rosbot
    tty: true      
    restart: on-failure
    network_mode: host
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
      - "SERIAL_PORT=/dev/ttyS1" # default: ttyS1 - rosbot2.0; ttyS4 - rosbot2.0 `pro
    devices:
      - "/dev/ttyS1"   # must match environment SERIAL_PORT 
    command: roslaunch rosbot_description rosbot_docker.launch
    

  # ROS Melodic Rplidar
  rplidar:
    image: husarion/rplidar:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - "ROS_IP=127.0.0.1"
      - "ROS_MASTER_URI=http://127.0.0.1:11311"
    devices:
      - /dev/ttyUSB0
    tty: true      
    command: roslaunch rplidar_ros rplidar_a2.launch # For Rosbot 2.0 PRO use roslaunch rplidar_ros rplidar_a3.launch