version: "2.3"

services:
  # ROS Noetic + ROS 2 Foxy
  bridge:
    image: ros:foxy-ros1-bridge
    restart: on-failure
    network_mode: host
    ipc: host
    environment:
      - "ROS_IP=$HOST_IP"
      - "ROS_MASTER_URI=http://$HOST_IP:11311"
      - "ROS_DOMAIN_ID=2"
    command: ros2 run ros1_bridge dynamic_bridge


  # ROS Noetic master
  my-ros-master:
    image: ros:noetic-ros-core
    restart: on-failure
    network_mode: host
    tty: true 
    environment:
      - "ROS_IP=$HOST_IP"
      - "ROS_MASTER_URI=http://$HOST_IP:11311"    
    command: stdbuf -o L roscore


  # ROS Melodic rosbot hardware layer
  rosbot:
    image: husarion/rosbot
    tty: true      
    restart: on-failure
    network_mode: host
    environment:
      - "ROS_IP=$HOST_IP"
      - "ROS_MASTER_URI=http://$HOST_IP:11311"
      - "SERIAL_PORT=/dev/ttyS4" # default: ttyS1 - rosbot2.0; ttyS4 - rosbot2.0 `pro
    privileged: false
    devices:
      - "/dev/ttyS4"   # must match environment SERIAL_PORT 
    command: roslaunch rosbot_description rosbot_docker.launch
    

  # ROS Melodic Rplidar
  rplidar:
    image: husarion/rplidar:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - "ROS_IP=$HOST_IP"
      - "ROS_MASTER_URI=http://$HOST_IP:11311"
    devices:
      - /dev/ttyUSB0
    tty: true      
    command: roslaunch rplidar_ros rplidar_a3.launch # For Rosbot 2.0 PRO use roslaunch rplidar_ros rplidar_a3.launch